title: partner-bootcamp-actions
description: GitHub Actions hands-on work for partner bootcamp.
template:
  repo: partner-bootcamp-actions-template
  name: partner-bootcamp-actions
before:
  - type: createIssue
    title: Setting up your environment!
    body: new-issue.md
    labels:
      - provision probot app
  - type: createPullRequest
    title: Creating Azure Resources
    body: create-azure-resources.md
    head: creating-azure-resources
steps:
  - title: First step
    description: The first step in your course
    event: pull_request.closed
    link: "{{ repoUrl }}"
    actions:
      # if the pull was merged then comment in the issue with steps
      # to trigger the workflow
    - type: gate
      every: true
      gates:
      - left: '%payload.action%'
        operator: ===
        right: closed
      - left: '%payload.pull_request.merged%'
        else:
          type: closeIssue
          issue: Setting up your environment!
          # else if pull was simply closed, then also close the issue
          # and don't comment
      - type: respond
        with: trigger-azure-config.md
        issue: Setting up your environment!
      # Respond with "all-set" for next class... see you soon!
