title: Partner Bootcamp Actions
description: GitHub Actions hands-on work for partner bootcamp.
template:
  name: partner-bootcamp-actions
  repo: partner-bootcamp-actions-template
before:
  - type: createLabel
    name: provision probot app
    color: 8132a8
  - type: createIssue
    title: "Activity 1: Setting up your environment!"
    body: new-issue.md
    labels: ["provision probot app"]
    store:
      EnvironmentIssueUrl: '{{ result.data.html_url }}'
      EnvironmentIssueNumber: '{{ result.data.number }}'
  - type: createPullRequest
    title: "Activity 2: Creating Azure Resources"
    body: create-azure-resources.md
    head: creating-azure-resources
    store:
      AzureSetupPRNumber: '{{ result.data.number }}'
      AzureSetupPRUrl: '{{ result.data.html_url }}'

  - type: createPullRequest
    title: "Activity 3: Add a CI/CD workflow"
    head: add-azure-ci-cd
    body: ci-cd-instructions.md

  - type: createPullRequest
    title: "Activity 4: Add a probot feature"
    head: add-probot-feature
    body: probot-feature-instructions.md

  - type: createPullRequest
    title: "Activity 5: Add a teardown workflow"
    head: destroying-azure-resources
    body: teardown-instructions.md



steps:
  - title: First step
    description: The first step in your course
    event: pull_request.closed
    link: "{{ store.EnvironmentIssueUrl }}"
    actions:
      # if the pull was merged then comment in the issue with steps
      # to trigger the workflow
      - type: gate
        left: '{{ payload.pull_request.merged }}'
        else:
          - type: closeIssue
            issue: '{{ store.EnvironmentIssueNumber }}'
          # else if pull was simply closed, then also close the issue
          # and don't comment
      - type: respond
        with: trigger-azure-config.md
        issue: "Activity 1: Setting up your environment!"
      # Respond with "all-set" for next class... see you soon!
